# Generated by Django 5.2.7 on 2026-02-08 18:53

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название тега')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемый тег')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Количество использований')),
                ('category', models.CharField(blank=True, choices=[('genre', 'Жанр'), ('fandom', 'Фэндом'), ('theme', 'Тема'), ('relationship', 'Отношения'), ('character', 'Персонаж'), ('other', 'Другое')], max_length=50, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Предлагаемый тег',
                'verbose_name_plural': 'Предлагаемые теги',
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название тега')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Количество использований')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Никнейм')),
                ('country', models.CharField(blank=True, choices=[('', 'Выберите страну...'), ('RU', 'Россия'), ('BY', 'Беларусь'), ('KZ', 'Казахстан'), ('UA', 'Украина'), ('AM', 'Армения'), ('AZ', 'Азербайджан'), ('GE', 'Грузия'), ('MD', 'Молдова'), ('UZ', 'Узбекистан'), ('TJ', 'Таджикистан'), ('TM', 'Туркменистан'), ('KG', 'Кыргызстан'), ('LV', 'Латвия'), ('LT', 'Литва'), ('EE', 'Эстония'), ('US', 'США'), ('DE', 'Германия'), ('FR', 'Франция'), ('IT', 'Италия'), ('ES', 'Испания'), ('UK', 'Великобритания'), ('CA', 'Канада'), ('AU', 'Австралия'), ('JP', 'Япония'), ('KR', 'Южная Корея'), ('CN', 'Китай'), ('BR', 'Бразилия'), ('IN', 'Индия'), ('PL', 'Польша'), ('CZ', 'Чехия'), ('SK', 'Словакия'), ('HU', 'Венгрия'), ('RO', 'Румыния'), ('BG', 'Болгария'), ('GR', 'Греция'), ('TR', 'Турция'), ('IL', 'Израиль'), ('AE', 'ОАЭ'), ('SA', 'Саудовская Аравия'), ('OTHER', 'Другая страна')], max_length=100, null=True, verbose_name='Страна')),
                ('phone', models.CharField(blank=True, help_text='Формат: +79991234567', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+999999999'. Максимум 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Номер телефона')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Fanfic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('content', models.TextField(verbose_name='Текст фанфика')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('archived', 'В архиве'), ('deleted', 'В корзине')], default='draft', max_length=20, verbose_name='Статус')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='Теги (через запятую)')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний просмотр')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления в корзину')),
                ('purge_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончательного удаления')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата архивации')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Фанфик',
                'verbose_name_plural': 'Фанфики',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('edited_count', models.PositiveIntegerField(default=0, verbose_name='Количество редактирований')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='users.comment', verbose_name='Родительский комментарий')),
                ('fanfic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.fanfic', verbose_name='Фанфик')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('notes', models.TextField(blank=True, help_text='Необязательные заметки к закладке', null=True, verbose_name='Заметки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('fanfic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='users.fanfic', verbose_name='Фанфик')),
            ],
            options={
                'verbose_name': 'Закладка',
                'verbose_name_plural': 'Закладки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ViewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата просмотра')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('fanfic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.fanfic', verbose_name='Фанфик')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История просмотра',
                'verbose_name_plural': 'История просмотров',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='users.comment', verbose_name='Комментарий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лайк комментария',
                'verbose_name_plural': 'Лайки комментариев',
                'indexes': [models.Index(fields=['comment', 'user'], name='users_comme_comment_f458d0_idx'), models.Index(fields=['created_at'], name='users_comme_created_35b0eb_idx')],
                'unique_together': {('comment', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='fanfic',
            index=models.Index(fields=['-views_count'], name='users_fanfi_views_c_9475e1_idx'),
        ),
        migrations.AddIndex(
            model_name='fanfic',
            index=models.Index(fields=['-created_at'], name='users_fanfi_created_909848_idx'),
        ),
        migrations.AddIndex(
            model_name='fanfic',
            index=models.Index(fields=['status'], name='users_fanfi_status_885f58_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['fanfic', 'parent'], name='users_comme_fanfic__7bd161_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author'], name='users_comme_author__0c82bd_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created_at'], name='users_comme_created_95fba1_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['is_deleted'], name='users_comme_is_dele_45cfc1_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['user', '-created_at'], name='users_bookm_user_id_636448_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['fanfic'], name='users_bookm_fanfic__18affd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'fanfic')},
        ),
        migrations.AddIndex(
            model_name='viewhistory',
            index=models.Index(fields=['user', '-viewed_at'], name='users_viewh_user_id_332113_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='viewhistory',
            unique_together={('user', 'fanfic')},
        ),
    ]
